################################# Default configuration ###################
baseURL = "https://antoinetavant.github.io/public/"  # For publication
# baseURL = "https://localhost:1313/"  # for developpement
title = "Antoine Tavant"
theme = "hello-friend"
publishDir = "docs"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  
############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################
[[menu.main]]
name = "About Us"
URL = "about"
weight = 1

[[menu.main]]
name = "Service"
URL = "services"
weight = 2

[[menu.main]]
name = "Portfolio"
URL = "portfolio"
weight = 3

[[menu.main]]
name = "Team"
URL = "team"
weight = 4

[[menu.main]]
name = "Pricing"
URL = "pricing"
weight = 5

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 6

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 7

#### external / static link ####
[[menu.static]]
name = "Themefisher"
URL = "https://themefisher.com/"
weight = 7


############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"

[languages]
  [languages.en]
    title = "Antoine Cosson-Tavant's personal site"
    subtitle = "Notes and thoughts of a normal guy"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by Antoine"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Antoine Cosson-Tavant's"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
        
  [languages.fr]
    title = "Site personnel d'Antoine Cosson-Tavant"
    subtitle = "Notes et pensées d'un gars normal"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Ecrit par Antoine"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.fr.params.logo]
      logoText = "Antoine Cosson-Tavant"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = "about"
        name = "A propos"
        url = "/about"
      [[languages.fr.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"